### ISSUE TITLE
Docker-compose up fails currently

### ISSUE THREAD

**Issue by geekpete** [nylas/sync-engine-docker#2]
Missing requirements.txt file.

**Comment by debelan** [comment]
same here. Bump.

**Comment by dalanmiller** [comment]
Just came across this as well. I wonder if the intention is to unzip this repo into the main repo of nylas/sync-engine and then run `docker-compose up`?

**Comment by YurySolovyov** [comment]
Seems like it should be that one - [`requirements.txt`](https://github.com/nylas/sync-engine/blob/master/requirements.txt), but I couldn't get it to build.
But I'm eager to try something if anyone has ideas.

**Comment by YurySolovyov** [comment]
I was able to build it with some tweaks, but looking at logs it seems like it is still not working.
My experimental repo is [`here`](https://github.com/YurySolovyov/sync-engine-docker)

**Comment by geekpete** [comment]
I sent a PR, but this repo seems not to have focus/priority currently.
https://github.com/nylas/sync-engine-docker/pull/1

**Comment by grinich** [comment]
You should consider this repo deprecated. Feel free to fork if you want. We'll have some news in a few weeks about better ways to use N1 without a cloud sync system.
